import { ThemeColor } from "./type";

export const themeMonokai: ThemeColor = {
    "--bigobjview-color": "#f8f8f2",
    "--bigobjview-bg-color": "#272822",
    "--bigobjview-change-color": "#f92672",
    "--bigobjview-fontsize": "12px",
    "--bigobjview-type-boolean-color": "#66d9ef",
    "--bigobjview-type-number-color": "#ae81ff",
    "--bigobjview-type-bigint-color": "#ae81ff",
    "--bigobjview-type-string-color": "#e6db74",
    "--bigobjview-type-object-array-color": "#a6e22e",
    "--bigobjview-type-object-object-color": "#fd971f",
    "--bigobjview-type-object-promise-color": "#f92672",
    "--bigobjview-type-object-map-color": "#66d9ef",
    "--bigobjview-type-object-set-color": "#fd971f",
    "--bigobjview-type-function-color": "#66d9ef",
    "--bigobjview-type-object-regexp-color": "#f92672",
    "--bigobjview-type-object-date-color": "#a6e22e",
    "--bigobjview-type-object-error-color": "#ff6188",
};

export const themeDracula: ThemeColor = {
    "--bigobjview-color": "#f8f8f2",
    "--bigobjview-bg-color": "#282a36",
    "--bigobjview-change-color": "#ff79c6",
    "--bigobjview-fontsize": "12px",
    "--bigobjview-type-boolean-color": "#8be9fd",
    "--bigobjview-type-number-color": "#bd93f9",
    "--bigobjview-type-bigint-color": "#bd93f9",
    "--bigobjview-type-string-color": "#f1fa8c",
    "--bigobjview-type-object-array-color": "#50fa7b",
    "--bigobjview-type-object-object-color": "#ffb86c",
    "--bigobjview-type-object-promise-color": "#ff79c6",
    "--bigobjview-type-object-map-color": "#8be9fd",
    "--bigobjview-type-object-set-color": "#ffb86c",
    "--bigobjview-type-function-color": "#8be9fd",
    "--bigobjview-type-object-regexp-color": "#ff5555",
    "--bigobjview-type-object-date-color": "#50fa7b",
    "--bigobjview-type-object-error-color": "#ff5555",
};

export const themeOneDark: ThemeColor = {
    "--bigobjview-color": "#abb2bf",
    "--bigobjview-bg-color": "#282c34",
    "--bigobjview-change-color": "#e06c75",
    "--bigobjview-fontsize": "12px",
    "--bigobjview-type-boolean-color": "#56b6c2",
    "--bigobjview-type-number-color": "#d19a66",
    "--bigobjview-type-bigint-color": "#d19a66",
    "--bigobjview-type-string-color": "#98c379",
    "--bigobjview-type-object-array-color": "#61afef",
    "--bigobjview-type-object-object-color": "#c678dd",
    "--bigobjview-type-object-promise-color": "#e06c75",
    "--bigobjview-type-object-map-color": "#56b6c2",
    "--bigobjview-type-object-set-color": "#e5c07b",
    "--bigobjview-type-function-color": "#61afef",
    "--bigobjview-type-object-regexp-color": "#e06c75",
    "--bigobjview-type-object-date-color": "#98c379",
    "--bigobjview-type-object-error-color": "#be5046",
};

export const themeMaterialDarker: ThemeColor = {
    "--bigobjview-color": "#eeffff",
    "--bigobjview-bg-color": "#1e1e24",
    "--bigobjview-change-color": "#ff5370",
    "--bigobjview-fontsize": "12px",
    "--bigobjview-type-boolean-color": "#82aaff",
    "--bigobjview-type-number-color": "#f78c6c",
    "--bigobjview-type-bigint-color": "#f78c6c",
    "--bigobjview-type-string-color": "#c3e88d",
    "--bigobjview-type-object-array-color": "#89ddff",
    "--bigobjview-type-object-object-color": "#ffcb6b",
    "--bigobjview-type-object-promise-color": "#c792ea",
    "--bigobjview-type-object-map-color": "#82aaff",
    "--bigobjview-type-object-set-color": "#f78c6c",
    "--bigobjview-type-function-color": "#89ddff",
    "--bigobjview-type-object-regexp-color": "#ff5370",
    "--bigobjview-type-object-date-color": "#c3e88d",
    "--bigobjview-type-object-error-color": "#ff5370",
};

export const themeGitHubLight: ThemeColor = {
    "--bigobjview-color": "#24292f",
    "--bigobjview-bg-color": "#ffffff",
    "--bigobjview-change-color": "#0969da",
    "--bigobjview-fontsize": "12px",
    "--bigobjview-type-boolean-color": "#0550ae",
    "--bigobjview-type-number-color": "#953800",
    "--bigobjview-type-bigint-color": "#953800",
    "--bigobjview-type-string-color": "#0a3069",
    "--bigobjview-type-object-array-color": "#116329",
    "--bigobjview-type-object-object-color": "#4d2d00",
    "--bigobjview-type-object-promise-color": "#bf3989",
    "--bigobjview-type-object-map-color": "#1b7c83",
    "--bigobjview-type-object-set-color": "#8250df",
    "--bigobjview-type-function-color": "#0a3069",
    "--bigobjview-type-object-regexp-color": "#cf222e",
    "--bigobjview-type-object-date-color": "#116329",
    "--bigobjview-type-object-error-color": "#cf222e",
};

export const themeSolarizedLight: ThemeColor = {
    "--bigobjview-color": "#657b83",
    "--bigobjview-bg-color": "#fdf6e3",
    "--bigobjview-change-color": "#d33682",
    "--bigobjview-fontsize": "12px",
    "--bigobjview-type-boolean-color": "#268bd2",
    "--bigobjview-type-number-color": "#d33682",
    "--bigobjview-type-bigint-color": "#d33682",
    "--bigobjview-type-string-color": "#2aa198",
    "--bigobjview-type-object-array-color": "#859900",
    "--bigobjview-type-object-object-color": "#b58900",
    "--bigobjview-type-object-promise-color": "#6c71c4",
    "--bigobjview-type-object-map-color": "#cb4b16",
    "--bigobjview-type-object-set-color": "#dc322f",
    "--bigobjview-type-function-color": "#268bd2",
    "--bigobjview-type-object-regexp-color": "#d33682",
    "--bigobjview-type-object-date-color": "#859900",
    "--bigobjview-type-object-error-color": "#dc322f",
};

export const themeQuietLight: ThemeColor = {
    "--bigobjview-color": "#333333",
    "--bigobjview-bg-color": "#f5f5f5",
    "--bigobjview-change-color": "#d67e2d",
    "--bigobjview-fontsize": "12px",
    "--bigobjview-type-boolean-color": "#007acc",
    "--bigobjview-type-number-color": "#a74cb4",
    "--bigobjview-type-bigint-color": "#a74cb4",
    "--bigobjview-type-string-color": "#a31515",
    "--bigobjview-type-object-array-color": "#1c6b48",
    "--bigobjview-type-object-object-color": "#ad8900",
    "--bigobjview-type-object-promise-color": "#c586c0",
    "--bigobjview-type-object-map-color": "#007acc",
    "--bigobjview-type-object-set-color": "#b76b01",
    "--bigobjview-type-function-color": "#267f99",
    "--bigobjview-type-object-regexp-color": "#d67e2d",
    "--bigobjview-type-object-date-color": "#1c6b48",
    "--bigobjview-type-object-error-color": "#c72e0f",
};

export const themeSepia: ThemeColor = {
    "--bigobjview-color": "#5b4636",
    "--bigobjview-bg-color": "#f4ecd8",
    "--bigobjview-change-color": "#a05f2c",
    "--bigobjview-fontsize": "12px",
    "--bigobjview-type-boolean-color": "#7f9c90",
    "--bigobjview-type-number-color": "#a05f2c",
    "--bigobjview-type-bigint-color": "#a05f2c",
    "--bigobjview-type-string-color": "#8b6f47",
    "--bigobjview-type-object-array-color": "#6f8f3d",
    "--bigobjview-type-object-object-color": "#b07d62",
    "--bigobjview-type-object-promise-color": "#a05f2c",
    "--bigobjview-type-object-map-color": "#7f9c90",
    "--bigobjview-type-object-set-color": "#b07d62",
    "--bigobjview-type-function-color": "#6f8f3d",
    "--bigobjview-type-object-regexp-color": "#a05f2c",
    "--bigobjview-type-object-date-color": "#8b6f47",
    "--bigobjview-type-object-error-color": "#9c4430",
};
