

export const ENUMERABLE_BIT = 1 << 0
export const EMPTY_CHILD_BIT = 1 << 2
export const NON_CIRCULAR_BIT = 1 << 8



export const META_DEFAULT_EXPAND = ENUMERABLE_BIT | NON_CIRCULAR_BIT
export const META_HASCHILD_MASK = ENUMERABLE_BIT | NON_CIRCULAR_BIT
export const META_HASCHILD_COND = ENUMERABLE_BIT | NON_CIRCULAR_BIT
