

export const ENUMERABLE_BIT = 1 << 0
export const EMPTY_CHILD_BIT = 1 << 2
export const DEFAULT_COLLAPSE = 1 << 3
export const NON_CIRCULAR_BIT = 1 << 8



export const META_DEFAULT_EXPAND = ENUMERABLE_BIT | NON_CIRCULAR_BIT
export const META_HASCHILD_MASK = EMPTY_CHILD_BIT | NON_CIRCULAR_BIT
export const META_HASCHILD_COND = NON_CIRCULAR_BIT
export const ENUMERABLE_BUT_COLLAPSE = ENUMERABLE_BIT | DEFAULT_COLLAPSE
